apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaccount-deployment
spec:
  selector:
    matchLabels:
      app: myaccount-pod
  replicas: 2    
  template:
    metadata:
      labels:
        app: myaccount-pod
    spec:
      containers:
      - name: myaccount-container
        image: myaccount:latest
        imagePullPolicy: AlwaysPullImages
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myaccount-service
spec:
  selector:
    app: myaccount-pod
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer  
